apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway.yaml
  - auth-service.yaml
  - course-service.yaml
  - enrollment-service.yaml
  - payment-service.yaml
  - media-service.yaml
  - lab-service.yaml
  - quiz-service.yaml
  - certificate-service.yaml
  - notification-service.yaml
  - web.yaml
